// FeeData.js
export const feeRecordsData = [
  {
    id: 1,
    studentId: 'CS21001',
    studentName: 'Rahul Sharma',
    course: 'B.Sc Computer Science',
    semester: '6th Semester',
    feeType: 'Semester Fee',
    amount: 15000,
    dueDate: '2023-06-15',
    status: 'Paid',
    paymentDate: '2023-06-10',
    paymentMethod: 'Online'
  },
  {
    id: 2,
    studentId: 'COM20015',
    studentName: 'Priya Patel',
    course: 'B.Com Accounting',
    semester: '4th Semester',
    feeType: 'Tuition Fee',
    amount: 12000,
    dueDate: '2023-06-20',
    status: 'Pending',
    paymentDate: '',
    paymentMethod: ''
  },
  {
    id: 3,
    studentId: 'BA21003',
    studentName: 'Amit Singh',
    course: 'B.A English',
    semester: '5th Semester',
    feeType: 'Examination Fee',
    amount: 3000,
    dueDate: '2023-05-30',
    status: 'Overdue',
    paymentDate: '',
    paymentMethod: ''
  },
  {
    id: 4,
    studentId: 'BSC20004',
    studentName: 'Neha Gupta',
    course: 'B.Sc Mathematics',
    semester: '6th Semester',
    feeType: 'Semester Fee',
    amount: 14000,
    dueDate: '2023-06-18',
    status: 'Paid',
    paymentDate: '2023-06-15',
    paymentMethod: 'Cash'
  },
  {
    id: 5,
    studentId: 'BBA21005',
    studentName: 'Vikram Joshi',
    course: 'BBA Management',
    semester: '2nd Semester',
    feeType: 'Library Fee',
    amount: 2000,
    dueDate: '2023-06-25',
    status: 'Pending',
    paymentDate: '',
    paymentMethod: ''
  },
  {
    id: 6,
    studentId: 'COM21006',
    studentName: 'Ananya Reddy',
    course: 'B.Com Finance',
    semester: '3rd Semester',
    feeType: 'Semester Fee',
    amount: 13000,
    dueDate: '2023-06-10',
    status: 'Paid',
    paymentDate: '2023-06-05',
    paymentMethod: 'Online'
  },
  {
    id: 7,
    studentId: 'CS20007',
    studentName: 'Rohan Malhotra',
    course: 'B.Sc Computer Science',
    semester: '4th Semester',
    feeType: 'Lab Fee',
    amount: 5000,
    dueDate: '2023-06-30',
    status: 'Pending',
    paymentDate: '',
    paymentMethod: ''
  },
  {
    id: 8,
    studentId: 'BA20008',
    studentName: 'Sneha Verma',
    course: 'B.A Psychology',
    semester: '6th Semester',
    feeType: 'Semester Fee',
    amount: 11000,
    dueDate: '2023-06-22',
    status: 'Paid',
    paymentDate: '2023-06-20',
    paymentMethod: 'Cheque'
  },
  {
    id: 9,
    studentId: 'BBA20009',
    studentName: 'Arjun Kapoor',
    course: 'BBA Marketing',
    semester: '4th Semester',
    feeType: 'Tuition Fee',
    amount: 16000,
    dueDate: '2023-05-25',
    status: 'Overdue',
    paymentDate: '',
    paymentMethod: ''
  },
  {
    id: 10,
    studentId: 'BSC21010',
    studentName: 'Isha Nair',
    course: 'B.Sc Physics',
    semester: '2nd Semester',
    feeType: 'Practical Fee',
    amount: 4000,
    dueDate: '2023-06-28',
    status: 'Pending',
    paymentDate: '',
    paymentMethod: ''
  },
  {
    id: 11,
    studentId: 'COM21011',
    studentName: 'Karan Mehta',
    course: 'B.Com Banking',
    semester: '5th Semester',
    feeType: 'Semester Fee',
    amount: 12500,
    dueDate: '2023-06-15',
    status: 'Paid',
    paymentDate: '2023-06-12',
    paymentMethod: 'Online'
  },
  {
    id: 12,
    studentId: 'BA21012',
    studentName: 'Divya Choudhary',
    course: 'B.A History',
    semester: '3rd Semester',
    feeType: 'Sports Fee',
    amount: 1500,
    dueDate: '2023-06-20',
    status: 'Pending',
    paymentDate: '',
    paymentMethod: ''
  },
  {
    id: 13,
    studentId: 'CS21013',
    studentName: 'Ravi Kumar',
    course: 'B.Sc Computer Science',
    semester: '2nd Semester',
    feeType: 'Development Fee',
    amount: 3500,
    dueDate: '2023-05-20',
    status: 'Overdue',
    paymentDate: '',
    paymentMethod: ''
  },
  {
    id: 14,
    studentId: 'BBA20014',
    studentName: 'Pooja Shah',
    course: 'BBA Finance',
    semester: '6th Semester',
    feeType: 'Semester Fee',
    amount: 15500,
    dueDate: '2023-06-18',
    status: 'Paid',
    paymentDate: '2023-06-15',
    paymentMethod: 'Cash'
  },
  {
    id: 15,
    studentId: 'BSC20015',
    studentName: 'Sahil Bhatia',
    course: 'B.Sc Chemistry',
    semester: '4th Semester',
    feeType: 'Lab Fee',
    amount: 6000,
    dueDate: '2023-06-25',
    status: 'Pending',
    paymentDate: '',
    paymentMethod: ''
  },
  {
    id: 16,
    studentId: 'COM20016',
    studentName: 'Meera Desai',
    course: 'B.Com Economics',
    semester: '5th Semester',
    feeType: 'Project Fee',
    amount: 2500,
    dueDate: '2023-06-30',
    status: 'Pending',
    paymentDate: '',
    paymentMethod: ''
  },
  {
    id: 17,
    studentId: 'BA21017',
    studentName: 'Aryan Singh',
    course: 'B.A Political Science',
    semester: '3rd Semester',
    feeType: 'Semester Fee',
    amount: 10000,
    dueDate: '2023-06-10',
    status: 'Paid',
    paymentDate: '2023-06-08',
    paymentMethod: 'Online'
  },
  {
    id: 18,
    studentId: 'BBA21018',
    studentName: 'Tanvi Patel',
    course: 'BBA Operations',
    semester: '2nd Semester',
    feeType: 'Activity Fee',
    amount: 1800,
    dueDate: '2023-06-22',
    status: 'Pending',
    paymentDate: '',
    paymentMethod: ''
  },
  {
    id: 19,
    studentId: 'BSC21019',
    studentName: 'Vivek Rao',
    course: 'B.Sc Biology',
    semester: '5th Semester',
    feeType: 'Field Trip Fee',
    amount: 4500,
    dueDate: '2023-05-30',
    status: 'Overdue',
    paymentDate: '',
    paymentMethod: ''
  },
  {
    id: 20,
    studentId: 'COM21020',
    studentName: 'Anjali Iyer',
    course: 'B.Com Statistics',
    semester: '6th Semester',
    feeType: 'Semester Fee',
    amount: 13500,
    dueDate: '2023-06-20',
    status: 'Paid',
    paymentDate: '2023-06-18',
    paymentMethod: 'Cheque'
  }
];