// AP Junior College Attendance Data

export const studentsData = [
  {
    id: 1,
    studentId: "MPC001",
    name: "Arjun Reddy",
    photo: "https://images.pexels.com/photos/3771118/pexels-photo-3771118.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "MPC",
    semester: 1,
  },
  {
    id: 2,
    studentId: "MPC002",
    name: "Priya Sharma",
    photo: "https://images.pexels.com/photos/3762804/pexels-photo-3762804.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "MPC",
    semester: 1,
  },
  {
    id: 3,
    studentId: "BiPC001",
    name: "Sneha Devi",
    photo: "https://images.pexels.com/photos/3771092/pexels-photo-3771092.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "BiPC",
    semester: 1,
  },
  {
    id: 4,
    studentId: "BiPC002",
    name: "Divya Lakshmi",
    photo: "https://images.pexels.com/photos/3771100/pexels-photo-3771100.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "BiPC",
    semester: 2,
  },
  {
    id: 5,
    studentId: "CEC001",
    name: "Kavya Rao",
    photo: "https://images.pexels.com/photos/3771113/pexels-photo-3771113.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "CEC",
    semester: 1,
  },
  {
    id: 6,
    studentId: "CEC002",
    name: "Karthik Nair",
    photo: "https://images.pexels.com/photos/3771107/pexels-photo-3771107.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "CEC",
    semester: 2,
  },
  {
    id: 7,
    studentId: "MEC001",
    name: "Vikram Rao",
    photo: "https://images.pexels.com/photos/3771089/pexels-photo-3771089.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "MEC",
    semester: 1,
  },
  {
    id: 8,
    studentId: "MEC002",
    name: "Ananya Gupta",
    photo: "https://images.pexels.com/photos/3771110/pexels-photo-3771110.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "MEC",
    semester: 2,
  },
  {
    id: 9,
    studentId: "HEC001",
    name: "Rohan Joshi",
    photo: "https://images.pexels.com/photos/3771095/pexels-photo-3771095.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "HEC",
    semester: 1,
  },
  {
    id: 10,
    studentId: "HEC002",
    name: "Sita Mahalakshmi",
    photo: "https://images.pexels.com/photos/3771119/pexels-photo-3771119.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "HEC",
    semester: 2,
  },
];

export const lecturersData = [
  {
    id: 1,
    lecturerId: "LEC001",
    name: "Mr. Ravi Kumar",
    photo: "https://images.pexels.com/photos/3762810/pexels-photo-3762810.jpeg?auto=compress&cs=tinysrgb&w=1200",
    courses: ["Mathematics", "Physics"],
  },
  {
    id: 2,
    lecturerId: "LEC002",
    name: "Ms. Priya Sharma",
    photo: "https://images.pexels.com/photos/3762800/pexels-photo-3762800.jpeg?auto=compress&cs=tinysrgb&w=1200",
    courses: ["Physics", "Chemistry"],
  },
  {
    id: 3,
    lecturerId: "LEC003",
    name: "Dr. Suresh Reddy",
    photo: "https://images.pexels.com/photos/3771120/pexels-photo-3771120.jpeg?auto=compress&cs=tinysrgb&w=1200",
    courses: ["Chemistry", "Biology"],
  },
  {
    id: 4,
    lecturerId: "LEC004",
    name: "Ms. Anjali Gupta",
    photo: "https://images.pexels.com/photos/3762812/pexels-photo-3762812.jpeg?auto=compress&cs=tinysrgb&w=1200",
    courses: ["Economics", "Commerce"],
  },
  {
    id: 5,
    lecturerId: "LEC005",
    name: "Mr. Krishna Murthy",
    photo: "https://images.pexels.com/photos/3771115/pexels-photo-3771115.jpeg?auto=compress&cs=tinysrgb&w=1200",
    courses: ["History", "Civics"],
  },
];